---
- name: " Copy Adobe Reader DC installer files from unc "
  win_copy:
    src: "{{mount_path}}{{adobe_reader_dc_src_dir}}"
    dest: "{{citrix_path}}"
    


- name: " Install Adobe Reader DC"
  win_package: 
    path: "{{citrix_path}}{{adobe_reader_dc_src_dir}}\\{{adobe_reader_dc_installer_name}}"
    product_id: "{{adobe_reader_dc_product_id}}"
    arguments: 
      - /sAll
      - /rs
    state: present
...

